version: "3.8"

services:

  postgresdb:
    image: postgres
    restart: always
#    ports:
#      - "5432:5432"
    environment:
      - POSTGRES_DB=Food_recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0147

  food-app:
    image: markodmutavdzic/food-app:1.4
    depends_on:
      - postgresdb
    ports:
      - "5000:5000"

